Add terms for bulk reports
libris/definitions pull request #504
Opened 2024-11-13 17:49 UTC by olovy

2024-11-13 17:56 UTC, niklasl commented on source/vocab/details.ttl
> +    sdo:domainIncludes :MediaObject, bulk:Execution ; #for event and bitstream?
+1 we should "appropriately" widen some of these domains.

2024-11-14 07:27 UTC, kwahlin requested changes
See comment. Otherwise LGTM!

2024-11-14 07:27 UTC, kwahlin commented on source/vocab/display.jsonld
> +        },
Copy-pasted? :slightly_smiling_face:

2024-11-14 07:28 UTC, kwahlin commented on source/vocab/display.jsonld
> +          "showProperties": [ "bulk:status" ]
Copy-pasted? :slightly_smiling_face:

2024-11-14 08:45 UTC, olovy commented on source/vocab/display.jsonld
> +          "showProperties": [ "bulk:status" ]
Yes! :pray:

2024-11-14 08:47 UTC, olovy commented on source/vocab/display.jsonld
> +          "showProperties": [ "bulk:status" ]
```suggestion
        "bulk:Execution": {
          "@id": "bulk:Execution-chips",
          "@type": "fresnel:Lens",
          "classLensDomain": "bulk:Execution",
          "showProperties": [ "bulk:status" ]
```

2024-11-14 08:48 UTC, merged